### ISSUE TITLE
Hacked core files

### ISSUE THREAD

**Issue by peterpeter** [cavo789/aesecure_quickscan#4]
Hi

Many thanks for your effort and for the script - seems to have been a lot of work.

Just so I've said it:
I have been working in a Joomla agency for over 10 years. In the past, when you still had to update Joomla by overwriting the files via FTP and not all (or the most) installations were up-to-date, we had many hacked Joomla, one or two per month for sure. 

Back then I used the JMSS script, which always scanned ALL files ( core files too):
https://github.com/btoplak/Joomla-Anti-Malware-Scan-Script--JAMSS- 

In almost all hacks, Joomla core files were manipulated too - and your script does not scan core files, if I have seen this correctly.

I haven't seen a hacked Joomla in a while (thanks to one-click-update), but I thought I'd mention it.

But otherwise great work - thanks. The php_grep script is also absolutely brilliant.

**Comment by cavo789** [comment]
Thanks @peterpeter , thanks for the message and the appreciation.

[quote]In almost all hacks, Joomla core files were manipulated too - and your script does not scan core files, if I have seen this correctly.[/quote]

This is not totally true.  My tool use hashes; let's see the file https://github.com/cavo789/aesecure_quickscan/blob/master/hashes/joomla/J!4.3.4.json.

I've a script (not yet released publicly) that generate a hash from every single files of Joomla. In the link I've just given here above, I've thus downloaded Joomla 4.3.4 on my disk and scan each files then generate a hash for each file; for instance `32547c8da57d2f298fca4763d1b7aa72`.  The filename is not important at all.

When scanning a file using Quickscan, I'll first generate a hash of the file present on your site. If I get the exact same hash, then I known it's a core file since I've retrieved it earlier in J 4.3.4.  I know it's a core file and, most important, I know it's a clean file.

This is why you think I don't scan core files, it's untrue. 

To check this, alter any files from your Joomla installation, add just one space or a `.` (dot) or a virus, ... the hash of that file won't be in my "hashes" file and thus the file will be scanned.

Hope this clarify how the tool is working.

Have a nice day.

**Comment by peterpeter** [comment]
Hi
Thank you very much for your explanations. Then my assumption was wrong, and I'm sorry about that. 
Probably because of this sentence in the description:
"In a fresh Joomla or WordPress installation, you'll have a very few files to scan since the native, core, files are whitelisted"

Please don't get me wrong, I didn't want to criticise you, I just wanted to share my experience with hacked sites. But if the core files are also checked, all the better. But as I said, I haven't seen a hacked customer site since the 'one-click-updater'.

And once again, thank you for your work and for making it available to everyone - that's great.

All the best
Roger

**Comment by cavo789** [comment]
Oh, really, don't think that!   If something can be improved (and in this case it's very simple, all I have to do is adapt my text), I'd appreciate knowing about it so that I can take action.

Thank you for proofreading and alerting me to the ambiguity of this sentence.

Updated: https://github.com/cavo789/aesecure_quickscan/commit/6502ceed2b77ed78126bc38ed32f6aece000fd44
